### ISSUE TITLE
Classification words importance

### ISSUE THREAD

**Issue by lspataro** [jessevig/bertviz#17]
Is there any way to use bertviz to visualise the importance of the different words respect to a given prediction of a classification task (BertClassifier)? 
Similar to this: https://docs.fast.ai/text.interpret.html#interpret

Thank you

**Comment by jessevig** [comment]
Good idea, and thanks for pointing me to that code. I've been experimenting with gradient-based sensitivity analysis on the attention weights (rather than the inputs), but the results weren't particularly interpretable. But I may revisit this with some of the newer fine-tuned models. I agree that this would be a useful analysis for the inputs, though it may overload the visualization. I'll think more about this. Thanks.

**Comment by Azharo** [comment]
I've been wondering how to do this as well as I want to try and visualize which words were most important to the classification. One idea I've had is (if I have 12 encoders in BERT and am only fine-tuning the 12th layer) to take the output of the 11th layer, the Wq, Wk, and Wv weights of the fine-tuned 12th layer and calculate the score manually. Would that be the correct way to think of it? I would essentially get the value score for each token in the input.

**Comment by zysNLP** [comment]
Hi, @jessevig Thanks for your great work. As @lspataro @Azharo mentioned, I want to ask some more details. Lets see an example below:
As we know, BERT/GPT2 accept datas in the form of "sentence label" or "s1, s2, label", which maybe means a text classify task and a NLI task, like these sentences:

Text classifies:
s1: The girl wears a red hat and dresses up like a princess. ---label "clothing"
s2: He went to play basketball after class. It seems not many people today. ---label "sport"
As we expected, the words hat and dress in s1, basketball in s2 should get more attentions or a greater weight.

NLIs:
**prompt**: Some people think that strict punishments for driving offenses are the key to reducing traffic accidents. 
**inference**: Government should invest more in non-profit advertisements， so that  they would improve people’s safety awareness potentially
**label**: 1
As we expected, the words driving offenses traffic accidents in prompt and government and safety awareness maybe get more attentions or a greater weight, so other words would get smaller.

We want to get results like these, maybe not a relatively complex visualization results as @jessevig showed, I think this work may need to be done in the last layer of Bert. Furthermore, I would like to see a process.
For example, when we focus on the word hat in s1 above, according to the result clothing, I would like to see how Bert focuses higher weight on hat step by step, which should be the result of a series of time series locking hat, but I am not clear about what it should be, hoping to get your answer. Thank you!

**Comment by diogocortiz** [comment]
Hi there, anyone working on this topic?

I am looking for a way to identify the most important words in a sentence classification task as well.

**Comment by dshahrokhian** [comment]
+1

**Comment by koren-v** [comment]
+1

**Comment by LMdeLiangMi** [comment]
same question here :)

**Comment by koren-v** [comment]
Hi, I did the implementation of some gradient-based algorithms, you can check it here: https://github.com/koren-v/Interpret 
(Integrated Gradients works pretty good compared to Smooth Grad)

**Comment by ssdorsey** [comment]
> 
> 
> Hi, I did the implementation of some gradient-based algorithms, you can check it here: https://github.com/koren-v/Interpret
> (Integrated Gradients works pretty good compared to Smooth Grad)

This looks great!

**Comment by ssdorsey** [comment]
I can definitely recommend captum as well, they have an example using BERT: https://captum.ai/tutorials/Bert_SQUAD_Interpret

**Comment by gcunhase** [comment]
+1

**Comment by jessevig** [comment]
Closing this issue as I feel it's out of scope for BertViz given the other available libraries.

**Comment by er-vishalgour** [comment]
> 

Yeah Same question
