### ISSUE TITLE
how to use BertForSequenceClassification class for tf checkpoint fine-tuned on sentence classification task(eg. GLUE task).

### ISSUE THREAD

**Issue by Surabhi-Kumari** [jessevig/bertviz#19]
model_type = 'bert'
model_version_3 = './bertviz/tests/saved_model'
model_config = './bertviz/tests/saved_model/bert_config.json'
do_lower_case = False
config = BertConfig.from_json_file(model_config)
model =  BertForSequenceClassification.from_pretrained(model_version_3, from_tf=True, config=config)
tokenizer = BertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
show(model, model_type, tokenizer, sentence_a, sentence_b)

I have tried this code, but it shows error:
AttributeError: 'BertForSequenceClassification' object has no attribute 'bias'

Also, I'm unable to pass parameter num_labels in BertForSequenceClassification.from_pretrained()
It was showing error: __init__() got an unexpected keyword argument 'num_label'

Help me to fix it.

Thanks.

**Comment by jessevig** [comment]
Hi,
Thanks for reporting this. A couple of things:
- Did you try "num_labels" instead of "num_label"?
- There are a couple of related issues on pytorch_transformers: https://github.com/huggingface/pytorch-transformers/issues/676 and https://github.com/huggingface/pytorch-transformers/issues/580 

If you're getting this error in  BertForSequenceClassification, and you can't find a solution in the issues above, you might consider opening an issue with pytorch_transformers (https://github.com/huggingface/pytorch-transformers) as they would probably be in a better position to help.

**Comment by Surabhi-Kumari** [comment]
Hi,

**Comment by Surabhi-Kumari** [comment]
Thanks for reply.
I had tried both things "num_labels" and "num_label", getting the same error.
I have referred to [ huggingface/pytorch-transformers#676](url), but unable to resolve this.

**Comment by DocIsenberg** [comment]
Hey, I was able to load tensorflow checkpoints for both the pytorch-transformers v1.0.0 and the bertviz packaged version by editing modeling_bert.py as follows:
At line 105, change `pointer = model` to
```
        if len(name) == 1:                                                                                                                                                                                                                                                      
            if type(model).__name__ == "BertForSequenceClassification":                                                                                                                                                                                                         
                pointer = model.classifier                                                                                                                                                                                                                                      
            else:                                                                                                                                                                                                                                                               
                continue                                                                                                                                                                                                                                                        
        else:                                                                                                                                                                                                                                                                   
            pointer = model
```
Unfortunately, I got stuck here, see attached image. The "Layer" dialog box has no options in it, and there's no visualization nor error, just ...blank. I assume that my model had its decoder stripped out from the finetuning stage (someone with more knowledge of the BERT finetuning scripts from Google could verify this?), so that may be the cause of this issue.
 That being said, it would be nice to visualize just the encoder self-attention (Sentence A -> Sentence A) in the absence of the decoder.

<img width="736" alt="Screen Shot 2019-10-16 at 12 15 42 PM" src="https://user-images.githubusercontent.com/2624762/66951486-56073780-f00f-11e9-8f3a-8898d6f0cc29.png">

**Comment by jessevig** [comment]
Thanks for sharing. BTW, the latest version of BertViz allows you to load a model directly using the transformers library, so this shouldn't be an issue going forward.

**Comment by chikubee** [comment]
@jessevig 
I fine-tuned bert for a classification task.
I mean to convert the tensorflow checkpoints to pytorch so that i can load the model into BertForSequenceClassification for visualization.

I used the following script
# Initialise a configuration according to your model
config = BertConfig.from_pretrained('bert-base-uncased')
config.num_labels=4
# You will need to load a BertForTokenClassification model
model = BertForSequenceClassification(config)

tf_checkpoint_path = init_checkpoint
# Load weights from tf checkpoint
load_tf_weights_in_bert(model, config, tf_checkpoint_path)

pytorch_dump_path = "./pytorch_bert_output"
# Save pytorch-model
print("Save PyTorch model to {}".format(pytorch_dump_path))
torch.save(model.state_dict(), pytorch_dump_path)

 I am getting the following error
BertForSequenceClassification object has no attribute 'bias'

Please help me out.
Thanks

**Comment by shishishu** [comment]
@chikubee 

Hello, I try to visualize fine-tuned BERT model with BertModel and similar error occurs: "AttributeError: 'BertModel' object has no attribute 'bias"

This error occurs in file: "...Lib\site-packages\transformers\modeling_bert.py" line 104 and you can disable related lines.

<img width="1016" alt="104" src="https://user-images.githubusercontent.com/20367654/76625677-c42a3900-6572-11ea-87b7-31b5197c8f13.PNG">

<img width="943" alt="015" src="https://user-images.githubusercontent.com/20367654/76625681-c5f3fc80-6572-11ea-8ad7-f6c7c155c777.PNG">

Let me know if any questions.
