### ISSUE TITLE
attention details

### ISSUE THREAD

**Issue by vr25** [jessevig/bertviz#27]
Hi,

I found a non-working colab notebook [here](https://colab.research.google.com/drive/1Nlhh2vwlQdKleNMqpmLDBsAwrv_7NnrB) while I was reading [here](https://www.kdnuggets.com/2019/03/deconstructing-bert-part-2-visualizing-inner-workings-attention.html).

I was wondering if there is any way to get the attention details including the keys and vectors.

Thanks!

**Comment by jessevig** [comment]
Thanks for pointing that out. That KDNuggets article is a bit out of date. You can find links to updated Colabs in the README. You can find the code that retrieves the queries and keys here: https://github.com/jessevig/bertviz/blob/master/bertviz/neuron_view.py . Note that it uses a forked version of Transformers in order to get the queries/keys.
