### ISSUE TITLE
No visualization on changing sentences

### ISSUE THREAD

**Issue by Varchita-Beena** [jessevig/bertviz#42]
If I am changing sentence then the visualization is coming. Why so?

**Comment by jessevig** [comment]
Hi, can you tell me which notebook you are using? Are you running it on your machine or in Colab? Thanks.

**Comment by Varchita-Lalwani** [comment]
Hey hii,
Thanks for replying. I used both colab and notebook of bert on Google colab only.
Regards,Varchita
 
 
  On Mon, Apr 6, 2020 at 6:04 PM, Jesse Vig<notifications@github.com> wrote:   


Hi, can you tell me which notebook you are using? Are you running it on your machine or in Colab? Thanks.

**Comment by jessevig** [comment]
Okay, thanks. Can you tell me the name of the notebook (e.g. "head_view_bert.ipynb"? There are a few different ones for bert. Also, are you able to share the code from the cell where you made the change? If the text is very long, that may cause an issue.

**Comment by Varchita-Lalwani** [comment]
I used neuron_view_bert.sentence_a = friends were so tired and restaurants were over expensive.sentence_b = they didn't get a chance to have food there.
 
 
  On Mon, Apr 6, 2020 at 6:13 PM, Jesse Vig<notifications@github.com> wrote:   


Okay, thanks. Can you tell me the name of the notebook (e.g. "head_view_bert.ipynb"? There are a few different ones for bert. Also, are you able to share the code from the cell where you made the change? If the text is very long, that may cause an issue.

**Comment by jessevig** [comment]
Okay, thanks. I was able to replicate this issue. In my case it seems that the scroll window in the last step auto-scrolled to the bottom; if I scrolled up after hovering in the last cell output I could see it. Are you able to use this workaround? Also, you shouldn't have this issue if you run on your local machine rather than in Colab. Will also investigate underlying issue but that may take a while. Please let me know if workaround helps, thanks.

**Comment by Varchita-Lalwani** [comment]
So when I ran the same code of yours with same sentences, the code is working but the visualisation is not visible and the same thing with changing the sentences.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 6, 2020 at 7:10 PM, Jesse Vig<notifications@github.com> wrote:   


Okay, thanks. I was able to replicate this issue. In my case it seems that the scroll window in the last step auto-scrolled to the bottom; if I scrolled up after hovering in the last cell output I could see it. Are you able to use this workaround? Also, you shouldn't have this issue if you run on your local machine rather than in Colab. Will also investigate underlying issue but that may take a while. Please let me know if workaround helps, thanks.

**Comment by jessevig** [comment]
Yes, even the same code has the issue. The neuron-view colab doesn't seem to work if you run it yourself. So I would suggest:
(1) Seeing if you can hover your cursor over the last output step and see if you can scroll up to make the output visible. 
(2) Running it in the notebook on your local machine.
Please let me know if either of these workarounds are successful for you. Thanks.
