### ISSUE TITLE
Attention visualization for RoBERTa is blank, raises KeyError using call_html()

### ISSUE THREAD

**Issue by seyonechithrananda** [jessevig/bertviz#47]
Hi @jessevig ,

Thank you so much for making this library. It's an incredibly effective and easy way to create beautiful attention visualizations. I'm currently trying to implement for a tutorial in the [DeepChem library](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/22_Transfer_Learning_With_HuggingFace_tox21.ipynb). However, I'm running into a multitude of issues. When I use the RoBERTa notebook code, it doesn't display anything and is blank:
<img width="1348" alt="Screen Shot 2020-06-19 at 11 07 07 PM" src="https://user-images.githubusercontent.com/46096704/85189959-b6770480-b281-11ea-8de8-daf6ab047456.png">

When I try to re-use the BERT colab code on RoBERTa, it throws the following error: 
<img width="1096" alt="Screen Shot 2020-06-19 at 11 09 00 PM" src="https://user-images.githubusercontent.com/46096704/85189977-e0c8c200-b281-11ea-9fb4-16ebe222f8b3.png">

I'm able to successfully run the example BERT code, it runs successfully, however:
<img width="1022" alt="Screen Shot 2020-06-19 at 11 10 03 PM" src="https://user-images.githubusercontent.com/46096704/85189997-05bd3500-b282-11ea-88c2-a5c49dce161f.png">

I'd love to get your advice on how I can fix this. I'm really interested in visualizing the attention using the library for validating the robustness of the model, and for future technical presentations and papers. 

The Colab notebook can be accessed [here](https://colab.research.google.com/drive/1ZIeY5f4AoIJQbgX0bXzd228rd1sUIxAh?usp=sharing).

Thanks!

**Comment by jessevig** [comment]
Hi, I've gotten a minimal example working for Roberta on Colab: https://colab.research.google.com/drive/1k6klsJXLjQeyQKlqXMVVL7axgWD0NGfy?usp=sharing

One known limitation of the tool is that it may not render properly if there are multiple instances of it in a single notebook, so that might be the cause of some of the blank results.  I hope to resolve that issue at some point.

Let me know if this helps.

**Comment by seyonechithrananda** [comment]
Thanks for replying so quickly! I've been able to get the standard Roberta models to work, but I'm more interested in visualizing the attention weights of my model, specifically. Its located on the Huggingface model hub [here](https://huggingface.co/seyonec/ChemBERTa-zinc250k-v1).

I've managed to get my uploaded model to work for both model view and head-by-head attention, but I'm still having trouble setting it up for the neuron view.

Is it possible to use custom models on the model hub as part of the neuron view? I tried adding the s3 paths for the merge, vocab and model files in the neuron_roberta scripts but that didn't fix the issue either.
![Screen Shot 2020-06-20 at 12 02 28 PM](https://user-images.githubusercontent.com/46096704/85206146-ebb93c00-b2ed-11ea-85f0-a7d5f161fb98.png)

**Comment by seyonechithrananda** [comment]
^I moved to local for the purpose of getting it to work, but will certainly try out your example on Colab for the tutorial.

**Comment by jessevig** [comment]
The neuron view is different from the other views because it uses a local, forked copy of the transformers library. The reason is that it needs access to the queries, keys, and values, which currently aren't returned by the huggingface API. You can see an example of where I changed the code here: https://github.com/jessevig/bertviz/blob/590c957799c3c09a4e1306b43d9ec10785e53745/bertviz/transformers_neuron_view/modeling_bert.py#L336

But the version of transformers being used for the neuron view is a bit old, so there might be some compatibility issues unfortunately. The only recommendation would be to modify your newer version of transformers to replicate the changes I made for the neuron view (namely, to pass back the query, key, and value vectors.

**Comment by seyonechithrananda** [comment]
Thanks for the help @jessevig! Will take a look at your fork and see if I can update it!
