### ISSUE TITLE
Neuron view: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by Jazzssmine** [jessevig/bertviz#60]
The Colab notebook link for BERT--Neuron view has the problem that says 'IndexError: too many indices for tensor of dimension 1'. I wonder how to fix it?

**Comment by jessevig** [comment]
Hmm, I haven't seen that one. Did you get the Colab from the bertviz README? There are some out-of-date colabs floating around out there.

**Comment by jessevig** [comment]
Also the colabs tend to be less reliable than running it locally.

**Comment by Jazzssmine** [comment]
Hi, I also try with jupyter notebook to run the Roberta Neuron view but still the same error.

**Comment by jessevig** [comment]
Have you modified the notebook in any way? I get this error if I change the notebook to import RobertaModel from the transformers library instead of the local version that lives inside of bertviz.transformers_neuron_view:

```
# from bertviz.transformers_neuron_view import RobertaModel, RobertaTokenizer
from transformers import RobertaModel, RobertaTokenizer
```

The modified versions of RobertaModel in bertviz.transformers_neuron_view is needed because it returns additional data that is needed in the neuron view.

Please let me know if this help.

**Comment by Jazzssmine** [comment]
Hi, I tried bertviz.transformers_neuron_view and there's no warnings. However there's no images either, by clicking 'Layer' I can't get any layer information.
