### ISSUE TITLE
Is there a way to visualize a BERTweet model with this?

### ISSUE THREAD

**Issue by floge2** [jessevig/bertviz#62]
I was wondering if I could load a fine-tuned BERTweet model into any of the existing visualizations or whether there is planned to be a version that supports BERTweet in the future.

I have used the code for my RoBERTa model before and I absolutely love the visualizations!!

**Comment by floge2** [comment]
I used the roberta version for head and model view and came up with the following adjustments:

from transformers import AutoModel, AutoTokenizer 

model_version = "vinai/bertweet-base"
model = AutoModel.from_pretrained(model_version, output_attentions=True)
tokenizer = AutoTokenizer.from_pretrained(model_version, normalization=True)

It works well - am I missing something? Otherwise, I would suggest adding BERTweet to the list of supported model. Still working on the neuron view though since I can't figure out the model_type yet.

**Comment by jessevig** [comment]
Thanks for your feedback, I'll look into adding some additional demo code. As for running BERTweet in the neuron view, a couple of options might be:
* Save the BERTweet model locally, e.g. by using `save_pretrained` with transformers.RobertaModel and then pass the directory rather than the model_version when instantiating bertviz.transformers_neuron_view.RobertaModel  
* Editing this code in bertviz.transformers_neuron_view.RobertaModel to include the new model versions:

```
GPT2_PRETRAINED_MODEL_ARCHIVE_MAP = {"gpt2": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-pytorch_model.bin",
                                     "gpt2-medium": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-medium-pytorch_model.bin",}
GPT2_PRETRAINED_CONFIG_ARCHIVE_MAP = {"gpt2": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-config.json",
                                      "gpt2-medium": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-medium-config.json"}
```
