### ISSUE TITLE
Visualizing attention between words and corresponding classes

### ISSUE THREAD

**Issue by arunraja-hub** [jessevig/bertviz#65]
I am using HF's Distillbert to predict punctuation for each word in a sequence.
For example, if the unpunctuated sentence is `My name is John` , the model will predict `space space space full_stop`
So how can I visualize attention between the input sentence and output token using BertViz?

**Comment by jessevig** [comment]
Hi @arunraja-hub, thanks for the question. Because BERT has an encoder-only architecture with self-attention, there isn't an explicit attention mechanism between the output token and the input sentence.  In this case, the output token is computed from the final layer's output at the position of the corresponding word in the input. So the punctuation for "John" is computed based on the final layer output at the position of "John". The attention between this position and other positions is the closest thing to what you are asking, but it's not a perfect match as the attention serves other purposes besides just making a prediction at that position.
