### ISSUE TITLE
Error in neuron view

### ISSUE THREAD

**Issue by BSharmi** [jessevig/bertviz#66]
Hello,

I was trying the demo notebook and while running the following line
`attn = attn_data['attn'][0]  # assume batch_size=1; shape = [num_heads, source_seq_len, target_seq_len]`
in the neuron_view.py got the error below
`TypeError: new(): invalid data type 'str'`

attn_data is a tensor of shape [1, 12, 15, 15] and I could not get either 'attn', or 'queries' or 'keys' in the attn_data for any layer which is obtained from the attn_data_list for each layer.  I can run the interactive demo on colab but get this error after I clone the rep and reproduce the codes on a jupyter notebook. 

Would really appreciate if I knew what did I miss.

Thank you!

**Comment by jessevig** [comment]
Hi, thanks for filing this. Which notebook did you start with? The neuron view has a different API compared to the model view and the head view, due to needing to access the query/key vectors. Have you tried the neuron-view specific notebooks, like this one: https://github.com/jessevig/bertviz/blob/master/neuron_view_bert.ipynb . Unfortunately it only works for older BERT, GPT-2 and RoBERTa models currently. I will highlight this point more clearly in the README.

**Comment by BSharmi** [comment]
Thanks for the response!
I encountered the error while running the colab code on my jupyter notebook. 

I was able to run the https://github.com/jessevig/bertviz/blob/master/neuron_view_bert.ipynb without any error. 

Thanks you!
