### ISSUE TITLE
Failure to display head_view for large token lengths

### ISSUE THREAD

**Issue by sourav-fai** [jessevig/bertviz#82]
When the number of tokens increases, the time taken to load the js visuals for attention increases exponentially, causing failures to even load the javascript. 
I tested for the maximum 512 tokens starting from 10 tokens

**Comment by jessevig** [comment]
Hi @sourav-fai, thanks for the issue. Yes the tool is designed for shorter inputs and may become slow or even fail with very long inputs unfortunately. One way to mitigate this issue is to only visualize a particular layer or layers at a time, as described here: https://github.com/jessevig/bertviz#filtering-layers .  However you may still run into issues if the input sequences are extremely long.
